name: Pre-Deploy Build

on:
  push:
    branches:
      - release-v**
      - main
  pull_request:
    types: [synchronize, reopened, opened]
    branches:
      - release-v**
      - main

jobs:
  build:
    # environment: ${{ contains(github.ref, 'refs/heads/main') && 'production' || (startsWith(github.ref, 'refs/heads/release') && 'release') || 'development' }}
    name: Pre-Deployment Build Job (For Error Check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout into repo
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> .env
          echo "FLASK_APP=${{ secrets.FLASK_APP }}" >> .env
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "FLASK_ENV=production" >> .env

      - name: Build Dockerized App
        run: ./scripts/docker/build.sh
